development:
  adapter: postgresql
  database: data_ex_delta_development
  host: localhost

test:
    adapter: postgresql
    database: data_ex_delta_test
    host: localhost


production:
    adapter: postgresql
    database: data_ex_delta_production
    host: localhost
