development:
  adapter: postgresql
  database: lab_cmpc_delta_development
  host: localhost

test:
    adapter: postgresql
    database: lab_cmpc_delta_test
    host: localhost


production:
    adapter: postgresql
    database: lab_cmpc_delta_production
    host: localhost
